CREATE DATABASE ECOMMERCE;
USE ECOMMERCE;

SELECT * FROM `CLEAN ECOMMERCE`;
ALTER TABLE `CLEAN ECOMMERCE` RENAME TO E_COMMERCE;
SELECT * FROM E_COMMERCE;

SELECT * FROM E_COMMERCE LIMIT 10;
SELECT count(*) FROM E_COMMERCE;
SELECT COUNT(DISTINCT CustomerID) FROM E_COMMERCE;
SELECT SUM(Quantity * Price) AS TOTALREVENUE FROM E_COMMERCE;

SELECT Product, SUM(Quantity) AS TOTALQUANTITY
FROM E_COMMERCE
GROUP BY Product
ORDER BY TOTALQUANTITY DESC
LIMIT 5; 

SELECT Product, SUM(Quantity * Price) AS REVENUE
FROM E_COMMERCE
GROUP BY Product
ORDER BY REVENUE DESC;

DESCRIBE E_COMMERCE;

SELECT * FROM E_COMMERCE;

ALTER TABLE E_COMMERCE
ADD COLUMN OrderDate_New Date;

UPDATE E_COMMERCE
SET OrderDate_New = STR_TO_DATE(OrderDate, '%d-%m-%Y');

SELECT OrderDate, OrderDate_New
FROM E_COMMERCE
LIMIT 10;

ALTER TABLE E_COMMERCE
DROP COLUMN OrderDate;

SELECT * FROM E_COMMERCE;

ALTER TABLE E_COMMERCE RENAME COLUMN OrderDate_New TO OrderDate;

ALTER TABLE E_COMMERCE
MODIFY CustomerID VARCHAR(100),
MODIFY CustomerName VARCHAR(100),
MODIFY Product VARCHAR(100),
MODIFY Category VARCHAR(100);

SELECT * FROM E_COMMERCE;

DESCRIBE E_COMMERCE;

-- Total Sales by Category
SELECT CATEGORY, SUM(QUANTITY * PRICE) AS TOTAL_SALES 
FROM E_COMMERCE
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;

-- AVERAGE ORDER VALUE(AOV)
SELECT AVG(QUANTITY * PRICE) AS AVERAGE_ORDER_VALUE 
FROM E_COMMERCE; 

-- Monthly Sales Trend 
SELECT 
DATE_FORMAT(ORDERDATE, '%Y-%m') AS MONTH,
SUM(QUANTITY * PRICE) AS TOTAL_SALES
FROM E_COMMERCE
GROUP BY DATE_FORMAT(ORDERDATE, '%Y-%m')
ORDER BY MONTH;

-- TOP 10 CUSTOMERS BY SPENDING
SELECT CUSTOMERNAME, FORMAT(SUM(QUANTITY * PRICE),0) AS TOTAL_SPENT
FROM E_COMMERCE
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_SPENT DESC
LIMIT 10; 

-- Total Sales by Product
SELECT PRODUCT, SUM(QUANTITY * PRICE) AS TOTAL_SALES
FROM E_COMMERCE
GROUP BY PRODUCT
ORDER BY TOTAL_SALES DESC;

-- Products with Sales Above Average
SELECT PRODUCT, SUM(QUANTITY * PRICE) AS TOTAL_SALES 
FROM E_COMMERCE
GROUP BY PRODUCT
HAVING TOTAL_SALES > (SELECT AVG(QUANTITY * PRICE) FROM E_COMMERCE)
ORDER BY TOTAL_SALES DESC;

SELECT * FROM E_COMMERCE;

-- Calculate Total Sales (Quantity * Price)
SELECT `ORDER ID`, CUSTOMERNAME, PRODUCT, QUANTITY, PRICE, (QUANTITY * PRICE) AS Total_Sales
FROM E_COMMERCE;

-- FIND TOTAL SALES PER CUSTOMER
SELECT CUSTOMERNAME, SUM(QUANTITY * PRICE) AS TOTAL_SALES
FROM E_COMMERCE
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_SALES DESC;

-- Total Sales Per Category
SELECT CATEGORY, SUM(QUANTITY * PRICE) AS TOTAL_SALES
FROM E_COMMERCE
GROUP BY CATEGORY
ORDER BY TOTAL_SALES DESC;

-- NUMBER OF ORDER PER CUSTOMER
SELECT CUSTOMERNAME, COUNT(`ORDER ID`) AS TOTAL_ORDERS
FROM E_COMMERCE
GROUP BY CUSTOMERNAME
ORDER BY TOTAL_ORDERS DESC;

-- MONTHLY SALES REPORT
SELECT DATE_FORMAT(ORDERDATE, '%Y-%m') AS MONTH, SUM(QUANTITY * PRICE) AS MONTHLY_SALES
FROM E_COMMERCE
GROUP BY DATE_FORMAT(ORDERDATE,'%Y-%m')
ORDER BY MONTHLY_SALES DESC;

-- TOP 5 BEST SELLING PRODUCTS
SELECT PRODUCT, SUM(QUANTITY) AS TOTAL_QUANTITY 
FROM E_COMMERCE
GROUP BY PRODUCT
ORDER BY TOTAL_QUANTITY DESC
LIMIT 5;

-- HIGHEST REVENUE GENERATING PRODUCT
SELECT PRODUCT, SUM(QUANTITY * PRICE) AS REVENUE
FROM E_COMMERCE
GROUP BY PRODUCT
ORDER BY REVENUE DESC 
LIMIT 1;

-- Customer Summary Using Window Functions
SELECT 
    CustomerName,
    COUNT(`Order Id`) AS Total_Orders,
    SUM(Quantity * Price) AS Total_Sales,
    RANK() OVER (ORDER BY SUM(Quantity * Price) DESC) AS Sales_Rank
FROM E_COMMERCE
GROUP BY CustomerName;

-- Identifying Repeat Customers
SELECT 
    CustomerName,
    COUNT(`Order Id`) AS Orders_Count
FROM E_COMMERCE
GROUP BY CustomerName
HAVING COUNT(`Order Id`) > 1;

-- High-Value Customer Identification
SELECT 
    CustomerName,
    SUM(Quantity * Price) AS Total_Sales
FROM E_COMMERCE
GROUP BY CustomerName
HAVING SUM(Quantity * Price) > (
    SELECT AVG(Total_Customer_Sales)
    FROM (
        SELECT SUM(Quantity * Price) AS Total_Customer_Sales
        FROM E_COMMERCE
        GROUP BY CustomerName
    ) AS T
);

-- Category-wise Top-Selling Product
SELECT *
FROM (
    SELECT 
        Category,
        Product,
        SUM(Quantity) AS Total_Qty,
        RANK() OVER (PARTITION BY Category ORDER BY SUM(Quantity) DESC) AS rnk
    FROM E_COMMERCE
    GROUP BY Category, Product
) AS x
WHERE rnk = 1;

-- Monthly Customer Retention Analysis
SELECT DISTINCT 
    t1.CustomerID,
    t1.CustomerName,
    DATE_FORMAT(t1.OrderDate, '%Y-%m') AS Month_Current,
    DATE_FORMAT(t2.OrderDate, '%Y-%m') AS Month_Next
FROM E_COMMERCE t1
JOIN E_COMMERCE t2
ON t1.CustomerID = t2.CustomerID
AND DATE_FORMAT(t2.OrderDate, '%Y-%m') = DATE_FORMAT(t1.OrderDate + INTERVAL 1 MONTH, '%Y-%m');

-- RFM Analysis
SELECT 
    CustomerID,
    CustomerName,
    DATEDIFF(CURDATE(), MAX(OrderDate)) AS Recency,
    COUNT(`Order Id`) AS Frequency,
    SUM(Quantity * Price) AS Monetary
FROM E_COMMERCE
GROUP BY CustomerID, CustomerName;






